knp_paginator:
    page_range: 5                       # plage de pages affichées
    default_options:
        page_name: page                 # nom du paramètre de page
        sort_field_name: sort           # nom du paramètre de tri
        sort_direction_name: direction  # nom du paramètre de direction du tri
        distinct: true                  # filtrer les résultats distincts
    template:
        pagination: 'pagination.html.twig'     # votre template personnalisé pour la pagination
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # template par défaut
